-- Optional Databricks/Delta Lake alternative.
-- BigQuery remains the selected target for this assignment submission.

CREATE SCHEMA IF NOT EXISTS de_test;

CREATE TABLE IF NOT EXISTS de_test.clientparameters (
  CODE BIGINT NOT NULL,
  CLIENTTYPE STRING NOT NULL,
  CLIENTPLATFORM STRING NOT NULL,
  NOTREAL BIGINT NOT NULL,
  LASTMODIFICATIONDATE TIMESTAMP NOT NULL
)
USING DELTA;

CREATE TABLE IF NOT EXISTS de_test.playertransactions_raw (
  CODE BIGINT NOT NULL,
  PLAYERCODE BIGINT NOT NULL,
  REQUESTDATE TIMESTAMP NOT NULL,
  ACCEPTDATE TIMESTAMP,
  AMOUNT DECIMAL(38, 9) NOT NULL,
  TYPE STRING NOT NULL,
  STATUS STRING NOT NULL,
  PAYMENTMETHOD STRING NOT NULL,
  PAYMENTSUBMETHOD STRING,
  COUNTRY STRING,
  CLIENTPARAMETERCODE BIGINT NOT NULL,
  FIRSTDEPOSIT BIGINT NOT NULL,
  LASTUPDATEDATE TIMESTAMP NOT NULL,
  INGESTION_TIMESTAMP TIMESTAMP NOT NULL
)
USING DELTA
PARTITIONED BY (DATE(INGESTION_TIMESTAMP));

CREATE TABLE IF NOT EXISTS de_test.playertransactions (
  CODE BIGINT NOT NULL,
  PLAYERCODE BIGINT NOT NULL,
  REQUESTDATE TIMESTAMP NOT NULL,
  ACCEPTDATE TIMESTAMP,
  AMOUNT DECIMAL(38, 9) NOT NULL,
  TYPE STRING NOT NULL,
  STATUS STRING NOT NULL,
  PAYMENTMETHOD STRING NOT NULL,
  PAYMENTSUBMETHOD STRING,
  COUNTRY STRING,
  CLIENTPARAMETERCODE BIGINT NOT NULL,
  FIRSTDEPOSIT BIGINT NOT NULL,
  LASTUPDATEDATE TIMESTAMP NOT NULL,
  DWH_CREATE_TIME TIMESTAMP NOT NULL,
  DWH_UPDATE_TIME TIMESTAMP NOT NULL
)
USING DELTA
PARTITIONED BY (DATE(REQUESTDATE));

MERGE INTO de_test.playertransactions AS target
USING (
  SELECT
    CODE,
    PLAYERCODE,
    REQUESTDATE,
    ACCEPTDATE,
    AMOUNT,
    TYPE,
    STATUS,
    PAYMENTMETHOD,
    PAYMENTSUBMETHOD,
    COUNTRY,
    CLIENTPARAMETERCODE,
    FIRSTDEPOSIT,
    LASTUPDATEDATE
  FROM (
    SELECT
      raw.*,
      ROW_NUMBER() OVER (
        PARTITION BY CODE
        ORDER BY LASTUPDATEDATE DESC, INGESTION_TIMESTAMP DESC
      ) AS row_num
    FROM de_test.playertransactions_raw AS raw
    WHERE raw.INGESTION_TIMESTAMP >= :data_interval_start
      AND raw.INGESTION_TIMESTAMP < :data_interval_end
  )
  WHERE row_num = 1
) AS source
ON target.CODE = source.CODE
WHEN MATCHED AND source.LASTUPDATEDATE >= target.LASTUPDATEDATE
  AND (
    NOT (source.STATUS <=> target.STATUS)
    OR NOT (source.AMOUNT <=> target.AMOUNT)
    OR NOT (source.ACCEPTDATE <=> target.ACCEPTDATE)
    OR NOT (source.LASTUPDATEDATE <=> target.LASTUPDATEDATE)
  ) THEN UPDATE SET
  STATUS = source.STATUS,
  AMOUNT = source.AMOUNT,
  ACCEPTDATE = source.ACCEPTDATE,
  LASTUPDATEDATE = source.LASTUPDATEDATE,
  DWH_UPDATE_TIME = current_timestamp()
WHEN NOT MATCHED THEN INSERT (
  CODE, PLAYERCODE, REQUESTDATE, ACCEPTDATE, AMOUNT, TYPE, STATUS,
  PAYMENTMETHOD, PAYMENTSUBMETHOD, COUNTRY, CLIENTPARAMETERCODE,
  FIRSTDEPOSIT, LASTUPDATEDATE, DWH_CREATE_TIME, DWH_UPDATE_TIME
) VALUES (
  source.CODE, source.PLAYERCODE, source.REQUESTDATE, source.ACCEPTDATE,
  source.AMOUNT, source.TYPE, source.STATUS, source.PAYMENTMETHOD,
  source.PAYMENTSUBMETHOD, source.COUNTRY, source.CLIENTPARAMETERCODE,
  source.FIRSTDEPOSIT, source.LASTUPDATEDATE, current_timestamp(), current_timestamp()
);
